name: Build container image

on:
  workflow_dispatch:
  push:
    paths:
      - 'builder.def'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget
      - name: Install Apptainer
        run: |
          wget https://github.com/apptainer/apptainer/releases/download/v1.1.0-rc.2/apptainer_1.1.0-rc.2_amd64.deb
          sudo apt-get install -y ./apptainer_1.1.0-rc.2_amd64.deb
      - uses: actions/checkout@v3
      - name: Build container
        run: sudo apptainer build container.sif builder.def
      - name: Login and deploy
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push container.sif "oras://ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}"
